sudo: false # use container-based infrastructure

language: java
jdk:
  - oraclejdk8 # test against version 1.8

cache:
  directories:
    - '$HOME/.gradle' # cache the gradle cache directory
    - '$HOME/.m2/repository' # cache the maven artifacts

before_install:
  - chmod +x gradlew # make gradlew script executable

install:
  - ./gradlew assemble

script:
  - ./gradlew check jacocoTestReport # perform tests and compile jacoco test reports

after_script:
  - ./gradlew coveralls # collect jacoco reports from subprojects send them to coveralls

deploy:
  provider: heroku
  api_key:
    secure: "eDQ7JbmS/941clBQNTGaOcI/FVztdcb/LRTGP2d9qHI/4erOuQIVmUdU6FUJOMpL6psB/U2I1LMo6Dx5KtnTwuvKdJZ1c+vQojvt0qZiuFRaD24kWRAk0wBG4ebPLbiAiTVZiJdm/DS3Ss5MjaeNtDaZwttapJ3b3Hfy16V0/uy0IG9Dw9AuwT+Udw70v95GN9TIRLRkZhwQFzAqdOxmMWgqTNZjUwaEbsX2XX/bMCCO4ZYixZQtkiIPOxT168JEbkJj679yJ9iAifgfms9GMQsHKQ5J7QG6IC4bRxab3Ev6XCYaRsnsXPpRULxpNx9hDIdMV1Wo79poe9GK+jQLFa+QtfKjM1GfgxqQx3xKTnJcBIe5c4gbzr9wZhQy1aDR7vNoYaiT4/T2y6+95DRP8KswWCYK2kU4ZFSOg+e8dUKOhA6i5HPCqu0kki3X4TZ+6Yfxds3tgjoM537BGsyfvVacQXH4KVfWbWeTjiqvy/l2ikt5BlT2hTKXqVafMWCqEI83z6AZjPYOqvyG5oAJUaakQUFFbuX1DbW86IN22D/EWthtjjrUY3pvyD2UHILzCHa14cdAmtya+pOMPzJXzPq3R8kHGGOTaVZuv0BfHesF3jv4ZnFnQ2J7JIFDxnnJNEFTietOTXuRmx0SpNXdvuntBssX6dvhkuJ10aITfuY="
  app: enigmatic-anchorage-9135
  on:
    repo: ChrisZhong/twitter-following-management-tool
